# Generated by Django 5.0 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.IntegerField()),
                ('vname', models.CharField(max_length=64)),
                ('vsal', models.FloatField()),
                ('vaddr', models.CharField(max_length=64)),
            ],
        ),
    ]
